name: chopper
description: Chopper is an http client generator using source_gen, inspired by Retrofit
version: 4.0.0-nullsafety.1
documentation: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: ">=0.13.0-nullsafety.0 <1.0.0"
  meta: ^1.3.0-nullsafety.6
  logging: ^1.0.0

dev_dependencies:
  test: ^1.16.4
  build_runner: ^1.12.1
  build_test: ^2.0.0
  coverage: ^1.0.2
# wait https://github.com/pulyaevskiy/test-coverage/pull/39
#  test_coverage:
#    git:
#      url: https://github.com/JEuler/test-coverage.git
#      ref: new-coverage
  http_parser: ^4.0.0
  pedantic: ^1.11.0
  chopper_generator:
    path: ../chopper_generator
